### ISSUE TITLE
Go back home only goes to spawn

### ISSUE THREAD

**Issue by HueboWasTaken** [Shop-kins/SubnauticaTwitchInteractionMod#38]
The "go back home" reward only teleports you to the shallows and not to the lifepod, which is an issue if someone has redeemed "find a really new home". I realise this is probably working as intended, but is there a way I could modify the code to make the "go back home" reward teleport me straight back to the lifepod?

**Comment by allaboutmike** [comment]
Yes, you could. Right now the code returns you to a random spot in the shallows, but you could grab the current coordinates for the escape pod and have the teleport land you there instead. The relevant code is in the FunZone.cs file.

**Comment by HueboWasTaken** [comment]
I don't know how to code :( if it's quick could someone tell me what to replace the safeshalllows code with?

**Comment by Shop-kins** [comment]
The code change for this has now been merged, we will test and release the new version when we're happy
