### ISSUE TITLE
The type or namespace name 'Newtonsoft' does not exist in the namespace 'Oculus'

### ISSUE THREAD

**Issue by brad811** [Shop-kins/SubnauticaTwitchInteractionMod#49]
Hey! I've been enjoying this mod, and was hoping to customize it, and have been coming across some problems.

The line `using Oculus.Newtonsoft.Json;` is causing the following error, preventing me from compiling:

`The type or namespace name 'Newtonsoft' does not exist in the namespace 'Oculus'`

I have tried adding every DLL I can locate in the Subnautica folder, I have tried updating 0Harmony, BepInEx, Newtonsoft.Json, QModInstaller, SMLHelper...

I tried switching the statement to:

`using Newtonsoft.Json;`

Which compiles successfully. But then I get this when launching Subnautica:

`TypeLoadException: Could not resolve type with token 010000a1 (from typeref, class/assembly Newtonsoft.Json.JsonConvert, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed)`

(I also tried manually installing Newtonsoft.Json 13.0.0.0, but it seems only versions 13.0.0.1 and 13.0.0.2 are available through nuget)

**Comment by brad811** [comment]
After trying many things, including completely uninstalling and reinstalling Subnautica and deleting my local clone of this repo and re-cloning, turns out Visual Studio was referencing the wrong `Newtonsoft.Json.dll`. You have to specifically tell it to use the one from `steamapps/common/Subnautica/Subnautica_Data/Managed`.

**Comment by allaboutmike** [comment]
Yeah sorry for not being able to respond sooner. I had wanted to double check the setup I have locally, but didn't get a chance to do so 😔. The other thing about this import in particular is that the version is different depending on the version of Subnautica you have. I believe that it will change once the next release happens, and we'll have to update the mod at that point too.

**Comment by brad811** [comment]
Ah, that makes sense. Thanks for the info!
